name: Trigger SIRIUS Data Update (to GitLab)
on:
  push:
    branches:
      - master
    paths:
      - 'spectrainterface/sirius.py' # if sirius is updated

jobs:
  ping-gitlab-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Update Version in GitLab
        env:
          GL_TOKEN: ${{ secrets.GITLAB_PAT }}

          TZ: America/Sao_Paulo 
        run: |
          # Create bot informations
          git config --global user.name "github-actions-bot"
          git config --global user.email "github-actions@github.com"

          # Cloning the GitLab repository
          git clone https://oauth2:${GL_TOKEN}@gitlab.com/lnls-ids/sirius-beamlines-data.git target_repo
          cd target_repo
          
          # Update the trigger file
          echo "Last update from GitHub spectrainterface at $(date '+%d/%m/%Y %H:%M:%S')" > trigger_version.txt
          
          # Add modifications and Commit
          git add trigger_version.txt          
          git commit -m "Trigger: spectrainterface/sirius.py updated in GitHub" || exit 0
          
          # push
          git push origin main